### ISSUE TITLE
More missing dependancies

### ISSUE THREAD

**Issue by MushroomCassette** [greyhavens/msoy#11]
Hey Michael,
I want to thank you for the jar dependancies, I installed them and it moved on past that, but now it is saying I need a bunch of .swc and .pom files that can't be found either.

1) org.osflash:signals:swc:0.8.1-ooo
2) com.threerings:toyboxlib:swc:1.0
3) com.threerings:whirledthanelib:swc:1.0
4) com.threerings:thane:swc:1.0
5) com.threerings:naryalib:swc:1.9
6) com.threerings:vilyalib:swc:1.1
7) com.threerings:orthlib:swc:0.9

for artifact:
org.apache.maven:super-pom:pom:2.0

I hate to bother you again, but could you please help with these?

**Comment by MushroomCassette** [comment]
I should add it's missing from both   ooo-public (http://ooo-maven.googlecode.com/hg/repository) and central (http://repo1.maven.org/maven2)

**Comment by TWSICommunity** [comment]
What! More dependencies are missing D: I thought that was the last one...

**Comment by samskivert** [comment]
No problem. Those are available here:

https://www.dropbox.com/s/bzjwqbbsjumslhv/more-msoy-artifacts.jar?dl=0
