### ISSUE TITLE
What Operating System Does Msoy use?

### ISSUE THREAD

**Issue by TWSICommunity** [greyhavens/msoy#12]
I've noticed some people did have some problems lately but what does the build support? I use Ubuntu  and windows where as windows does not like the build error it has but with ubuntu (linux based) It works as long as you have the proper requirements such as Flex SDK and thane plus the artifacts. Which operating system would fit the best for building whirled and such? I'm just curious to know if you don't mind me asking that as I know your busy and all but this is a question I might need to know. You don't have to answer if you don't want to I was just curious is all.

**Comment by samskivert** [comment]
Any Unix-based operating system should be fine. So any Linux, Mac OS, and also FreeBSD.
