### ISSUE TITLE
More missing artifacts

### ISSUE THREAD

**Issue by Shadowsych** [greyhavens/msoy#16]
1) com.threerings:narya-gwt:jar:1.8

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=com.threerings -DartifactId=narya-gwt -Dversion=1.8 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=com.threerings -DartifactId=narya-gwt -Dversion=1.8 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
   1) org.apache.maven:super-pom:pom:2.0
   2) com.threerings:narya-gwt:jar:1.8

2) com.threerings:orth-gwt:jar:0.9

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=com.threerings -DartifactId=orth-gwt -Dversion=0.9 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=com.threerings -DartifactId=orth-gwt -Dversion=0.9 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
   1) org.apache.maven:super-pom:pom:2.0
   2) com.threerings:orth-gwt:jar:0.9

3) com.threerings:threerings:jar:1.0

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=com.threerings -DartifactId=threerings -Dversion=1.0 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=com.threerings -DartifactId=threerings -Dversion=1.0 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
   1) org.apache.maven:super-pom:pom:2.0
   2) com.threerings:underwire:jar:1.0
   3) com.threerings:threerings:jar:1.0

4) com.threerings:underwire-gwt:jar:1.0

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=com.threerings -DartifactId=underwire-gwt -Dversion=1.0 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=com.threerings -DartifactId=underwire-gwt -Dversion=1.0 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
   1) org.apache.maven:super-pom:pom:2.0
   2) com.threerings:underwire-gwt:jar:1.0

----------
4 required artifacts are missing.

for artifact: 
  org.apache.maven:super-pom:pom:2.0

from the specified remote repositories:
  ooo (http://build.earth.threerings.net/maven-repository),
  central (http://repo1.maven.org/maven2)

Total time: 7 seconds

------------------------------------------------------------------------------------------------------------------------
The artifacts missing are:
1. com.threerings:narya-gwt:jar:1.8
2. com.threerings:orth-gwt:jar:0.9
3. com.threerings:threerings:jar:1.0
4. com.threerings:underwire-gwt:jar:1.0

I looked through the Maven repositories, and none of the files are in the threerings folders.
Please give us the missing artifacts... We desperately rely on you Michael to give us the jars, thank you.

**Comment by samskivert** [comment]
https://dl.dropboxusercontent.com/u/404021/yet-more-msoy-artifacts.jar
