### ISSUE TITLE
Even MORE missing artifacts!

### ISSUE THREAD

**Issue by Shadowsych** [greyhavens/msoy#17]
1) nochump:zip:swc:1.0

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=nochump -DartifactId=zip -Dversion=1.0 -Dpackaging=swc -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=nochump -DartifactId=zip -Dversion=1.0 -Dpackaging=swc -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
   1) org.apache.maven:super-pom:pom:2.0
   2) nochump:zip:swc:1.0

2) com.adobe:as3corelib:swc:0.93

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=com.adobe -DartifactId=as3corelib -Dversion=0.93 -Dpackaging=swc -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=com.adobe -DartifactId=as3corelib -Dversion=0.93 -Dpackaging=swc -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
   1) org.apache.maven:super-pom:pom:2.0
   2) com.threerings:naryalib:swc:1.9
   3) com.adobe:as3corelib:swc:0.93

3) as3isolib:as3isolib-fp9:swc:r298

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=as3isolib -DartifactId=as3isolib-fp9 -Dversion=r298 -Dpackaging=swc -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=as3isolib -DartifactId=as3isolib-fp9 -Dversion=r298 -Dpackaging=swc -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
   1) org.apache.maven:super-pom:pom:2.0
   2) com.threerings:vilyalib:swc:1.1
   3) as3isolib:as3isolib-fp9:swc:r298

4) com.threerings:nenyalib:swc:1.0

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=com.threerings -DartifactId=nenyalib -Dversion=1.0 -Dpackaging=swc -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=com.threerings -DartifactId=nenyalib -Dversion=1.0 -Dpackaging=swc -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
   1) org.apache.maven:super-pom:pom:2.0
   2) com.threerings:vilyalib:swc:1.1
   3) com.threerings:nenyalib:swc:1.0

5) com.threerings:whirledlib:swc:1.1-SNAPSHOT

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=com.threerings -DartifactId=whirledlib -Dversion=1.1-SNAPSHOT -Dpackaging=swc -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=com.threerings -DartifactId=whirledlib -Dversion=1.1-SNAPSHOT -Dpackaging=swc -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
   1) org.apache.maven:super-pom:pom:2.0
   2) com.threerings:whirledlib:swc:1.1-SNAPSHOT

----------
5 required artifacts are missing.

for artifact: 
  org.apache.maven:super-pom:pom:2.0

from the specified remote repositories:
  ooo-public (http://ooo-maven.googlecode.com/hg/repository),
  central (http://repo1.maven.org/maven2)

Total time: 45 seconds
--------------------------------------------------------------------------------------------------------------------------
I appreciate the last question's quick reply. Let's hope you can reply fast again Michael!
Here's even more artifacts that are missing.

1. nochump:zip:swc:1.0
2. com.adobe:as3corelib:swc:0.93
3. as3isolib:as3isolib-fp9:swc:r298
4. com.threerings:nenyalib:swc:1.0
5. com.threerings:whirledlib:swc:1.1-SNAPSHOT

Thanks once again, we cannot do this without your help.

**Comment by samskivert** [comment]
https://dl.dropboxusercontent.com/u/404021/even-more-msoy-artifacts.jar

**Comment by NickVst** [comment]
The link to this artifact has since died. Is there any chance you could re-upload it?

**Comment by Shadowsych** [comment]
Hey NickVst, contact me via my email if you want the artifacts: pravat.bhusal@gmail.com

**Comment by NickVst** [comment]
Unfortunately it seems like this conversation bore no fruit.

@samskivert Could I re-ask you to re-upload the even-more-msoy-artifacts.jar file?

**Comment by Maxxiet** [comment]
I can upload the artifacts somewhere if I remember- I downloaded them all when they were originally up and they should be in my drive. :) I'm about to head to bed at the moment, though.

**Comment by samskivert** [comment]
I guess Dropbox decided to invalidate all links to Public folder files at some point in the past. Yay.

Here's a new link to the file that has been there the whole time:

https://www.dropbox.com/s/858r4u2k2bp1ng5/even-more-msoy-artifacts.jar?dl=0
