### ISSUE TITLE
Unable to get dependency information from the swc artifact.

### ISSUE THREAD

**Issue by Shadowsych** [greyhavens/msoy#18]
/home/whirledtest/Desktop/msoy/build.xml:165: Unable to resolve artifact: Unable to get dependency information: Unable to read the metadata file for artifact 'com.threerings:whirledlib:swc': Cannot find parent: com.threerings:whirled-api-parent for project: null:whirledlib:swc:null for project null:whirledlib:swc:null
  com.threerings:whirledlib:swc:1.1-SNAPSHOT

from the specified remote repositories:
  ooo-public (http://ooo-maven.googlecode.com/hg/repository),
  ooo (https://build.earth.threerings.net/maven-repository),
  central (http://repo1.maven.org/maven2),
  as3corelib-repo (https://github.com/samskivert/as3corelib/raw/master/repository)

Path to dependency: 
 1) org.apache.maven:super-pom:pom:2.0
 2) com.threerings:orthlib:swc:0.9

Total time: 16 seconds
----------------------------------------------------------------------------------------------------------------------
Hey Michael, the build cannot receive the dependency information from the whirled-api parent.
We have the whirled-api-parent in the com/threerings/ file path and the snapshot is set up inside a folder. 

Thanks, I hope for a fast reply.

**Comment by samskivert** [comment]
I think you need this:

https://dl.dropboxusercontent.com/u/404021/whirled-api-parent.jar
