### ISSUE TITLE
Even MORE MORE artifacts are missing!

### ISSUE THREAD

**Issue by Shadowsych** [greyhavens/msoy#19]
1) as3isolib:as3isolib-fp9:swc:r298

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=as3isolib -DartifactId=as3isolib-fp9 -Dversion=r298 -Dpackaging=swc -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=as3isolib -DartifactId=as3isolib-fp9 -Dversion=r298 -Dpackaging=swc -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
   1) org.apache.maven:super-pom:pom:2.0
   2) com.threerings:vilyalib:swc:1.1
   3) as3isolib:as3isolib-fp9:swc:r298

----------
1 required artifact is missing.

for artifact: 
  org.apache.maven:super-pom:pom:2.0

from the specified remote repositories:
  ooo-public (http://ooo-maven.googlecode.com/hg/repository),
  central (http://repo1.maven.org/maven2)

Total time: 18 seconds

------------------------------------------------------------------------------------------------------------------------
Hey Michael,
1 Artifact is missing this time.

1.  as3isolib:as3isolib-fp9:swc:r298

Fast replies are great, aren't they?

**Comment by samskivert** [comment]
You caught me at a good time, so hopefully we can make it through all of these missing artifacts:

https://dl.dropboxusercontent.com/u/404021/as3isolib.jar

**Comment by Shadowsych** [comment]
Good that the artifact was given, we will reply soon if there are any errors. Currently we're (my partner and I) compiling the java environment for msoy since ant build told us we need to setup the java jdk with the program.

**Comment by Shadowsych** [comment]
To fix the java environment problem get java jre-6 using this command on ubuntu:

sudo apt-get update
