### ISSUE TITLE
Compiling Whirled Source Code

### ISSUE THREAD

**Issue by VoxRatio** [greyhavens/msoy#2]
Hey again Michael,

Could you please explain in as much detail as you can how to compile and any errors people may come across?

Thanks,
VoxRatio

**Comment by samskivert** [comment]
Sorry, that's exactly the sort of thing I don't have time for. You can start by running:
```
ant distcleanall
ant distall
```
and then see what fails and start trying to fix it, but I don't have time to document the entire set of dependencies and build process.
