### ISSUE TITLE
Cannot convert .swfs to .abcs

### ISSUE THREAD

**Issue by Shadowsych** [greyhavens/msoy#22]
thane-client:
     [java] Loading configuration file /home/whirledtest/Desktop/msoy/dist/thane-config.xml
     [java] /home/whirledtest/Desktop/msoy/dist/msoylib.swc (395657 bytes)
     [java] Loading configuration file /home/whirledtest/Desktop/msoy/dist/thane-config.xml
     [java] /home/whirledtest/Desktop/msoy/dist/MsoyThaneClient.swf (768 bytes)
     [echo] Turning .swfs into .abcs...

BUILD FAILED
/home/whirledtest/Desktop/msoy/build.xml:649: Java returned: 1

Total time: 1 minute 17 seconds
---------------------------------------------------------------------------------------------------
We configured the thane-config.xml and the msoy-config.xml directories to our Flex SDK version 3.3.
Which worked for us.

Now we are getting this error whenever the .swfs turn into .abcs it tells us the build has failed. 

Error was on line 649 in the build.xml
Line 649:       classname="flash.swf.tools.SwfxPrinter" fork="true" failonerror="true">

According to the XML code, I'm guessing it's trying to fork the SwfXPrinter class but cannot successfully do it.  Do you have any idea on doing so?

We do have the 3 jar files in the lib that you said are necessary to create the .abc files.

**Comment by Shadowsych** [comment]
Please reply, we need your help and experience building this project.

Thanks.

**Comment by TWSICommunity** [comment]
Do we just need the .abc files or like what command do we use to get those .abc files.

**Comment by Shadowsych** [comment]
Hello Michael, we are still awaiting a reply.

**Comment by TWSICommunity** [comment]
We aren't trying to rush you samskivert. You can always take your time into replying. What do we exactly do with the jar files that are used to gen ABC files?

**Comment by Shadowsych** [comment]
Although we're still on this error, I want to note to anyone listening that if you see an error with the invalid command '-k' (when building the command gclients) in your gzip, then update gzip to 1.6+ to work properly.

We are still on the SWF to ABC error, but I just wanted to note that out to anyone.

**Comment by Shadowsych** [comment]
We are still on this error, but we fixed the BUILD FAILED whenever we built using the "viewer" command. 

(Step 1 Fix) Change the build-support.xml file directories error line of ${flex.dir} to the actual directories  ^^^ There are 2 places to do this at.
(Step 2 Fix) Go to line 599 in the build.xml and remove the / on export.
(Step 3 Fix OPTIONAL) Create a manual folder on the msoy folder of: export/whirled/lib

We are still on the SWF to ABC error, but I just wanted to note that out to anyone.

**Comment by Shadowsych** [comment]
Although we're still on this error, we got the genasync build to fix.
How we fixed it:

1. Download the genasync.jar from samskivert's Github repository
2. Put the jar in the lib for msoy
3. Goto the build.xml in line 866 and change the file directory to the genasync.jar
4. Finished

We are still on the SWF to ABC error, but I just wanted to note that out for anyone else, even though we're kinda working ahead while waiting for Michael to reply.

**Comment by Shadowsych** [comment]
When we did genasync we had errors with the test, compile, and gclients command that made the Build Failed.

How we fixed that:
1. Goto AppServiceAsync.java, then find updateTemplates method

2. Change the updateTemplates method to  void updateTemplates (int appId, Set<FacebookTemplate> changed, Set<FacebookTemplate.Key> removed, Map<FacebookTemplate.Key, Boolean> abled, AsyncCallback<Void> callback);

3. Finished

We are still on the SWF to ABC error, but I just wanted to note that out for anyone else, even though we're kinda working ahead while waiting for Michael to reply. With all these other errors being fixed, it's best that we post it here for future references since there's no documentation on building Whirled.

The SWF to ABC error is what we speculate to be the LAST error before Whirled can completely be built!

**Comment by TWSICommunity** [comment]
Yup the last one I hope. :+1:

**Comment by Shadowsych** [comment]
We fixed the .abc to swf error after a week of work and research!
It really sucks with this lack of documentation, but with enough .XML knowledge we were able to fix it.
The problem is with the ANT-BUILD not being able to find the SwfxPrinter class within the swf-utils-ooo.jar

Here is how to fix it:
1. Goto the build.xml
1. Go to the line where it says "Turning .swfs to .abcs"
2. From line 643 to line 659 remove it and replace it with:

```
   <java outputproperty="dump" classname="flash.swf.tools.SwfxPrinter" fork="true" failonerror="true">
      <classpath>
        <fileset dir="/home/whirledtest/Desktop/msoy/lib">
          <include name="swfutils-ooo.jar"/>
          <include name="asc.jar"/>
        </fileset>
      </classpath>
      <arg value="-dump"/>
      <arg value="${deploy.dir}/msoylib.abc"/>
      <arg value="${deploy.dir}/msoylib.swc"/>
    </java>
    <java outputproperty="dump" classname="flash.swf.tools.SwfxPrinter" fork="true" failonerror="true">
      <classpath>
        <fileset dir="/home/whirledtest/Desktop/msoy/lib">
          <include name="swfutils-ooo.jar"/>
          <include name="asc.jar"/>
        </fileset>
      </classpath>
      <arg value="-dump"/>
      <arg value="${deploy.dir}/MsoyThaneClient.abc"/>
      <arg value="${deploy.dir}/MsoyThaneClient.swf"/>
    </java>
```

3. Where it says <fileset dir="/home/whirledtest/Desktop/msoy/lib"> change that to your msoy lib directory.
4. DONE

**Comment by Shadowsych** [comment]
We have successfully ran ant distall with NO MORE BUILD ERRORS :D! We are ready to proceed with the .bin/msoyserver build command.
