### ISSUE TITLE
Oh Noez! page

### ISSUE THREAD

**Issue by VoxRatio** [greyhavens/msoy#23]
TWSI, Shadow and I managed to successfully build and run the msoy server.
Now that the msoy server is running, we can go to localhost:8080, but we're greeted with the familiar page that says "We're not in Kansas any more Toto!". 

The console reports that the server is running smoothly, as shown below:

`user@msoy:~/Desktop/msoyfiles/msoy$ ./bin/msoyserver
`
`2016-07-22 21:23:19,876 INFO Logger: No AMQP messaging server configured.
`
`2016-07-22 21:23:27,019 INFO Logger: Starting up [server=MsoyServer, os=Linux (3.19.0-25-generic-amd64), jvm=1.6.0_39, Sun Microsystems Inc.]
`
`2016-07-22 21:23:27,125 INFO Logger: Running thane bureaus locally
`
`2016-07-22 21:23:27,151 INFO Slf4jLog: Logging to org.slf4j.impl.Log4jLoggerAdapter(org.mortbay.log) via org.mortbay.log.Slf4jLog
`
`2016-07-22 21:23:27,269 INFO Logger: Running in cluster mode as node 'msoy1'.
`
`2016-07-22 21:23:27,314 INFO Logger: Scheduling reboot on Sat Jul 23 01:00:00 AEST 2016 for automatic.
`
`2016-07-22 21:23:27,427 INFO Slf4jLog: jetty-6.1.25
`
`2016-07-22 21:23:27,452 INFO Logger: Underwire servlet initialized.
`
`2016-07-22 21:23:27,578 INFO Slf4jLog: Started MsoyHttpServer$MsoyChannelConnector@0.0.0.0:8080
`
`2016-07-22 21:23:27,604 INFO Logger: Policy server listening on port 47623.
`
`2016-07-22 21:23:27,621 INFO Logger: Msoy server initialized.
`
`2016-07-22 21:23:27,623 INFO Logger: DOMGR running.
`
`2016-07-22 21:23:27,643 INFO Logger: Server listening on 0.0.0.0/0.0.0.0:47624.`

We're so close to having a test instance up and running, but this seems to be the final hurdle.
Any help would be greatly appreciated.

Thanks,
VoxRatio.

**Comment by Shadowsych** [comment]
When we tested the .bin/msoyserver it turns out the ant viewer command wasn't working. 

We fixed viewer command by changing the file directories in the build.xml for the flex3.dir so that the viewer.swf could successfully copy into the file directories. We also manually created the msoy/export/lib file directory that the viewer is supposed to be copied towards. 

The localhost:8080 is still shown the O Noez! page, though. I just wanted to say that in case we will need it for further documentation.

**Comment by Shadowsych** [comment]
We fixed the error! How we did it:

Go to msoy-server.properties
Then go to line 79
Change the server_root to equal to where your msoy directory is at.
Restart your msoyserver (.bin/msoyserver) and you will be done!

We see the Whirled instance on our computer asking us to sign up and all! Currently we're installing Adobe Flash Player so we can test it out :).
