### ISSUE TITLE
[Whirled Instance] Stuck at 80%

### ISSUE THREAD

**Issue by Shadowsych** [greyhavens/msoy#25]
Hey Michael,

we've gotten the servers, database, and build to successfully run. We even have the website up and running on our public-test-domain (admins only right now); however, the world-client.swf does not go past 80%. 

![whirledloading](https://cloud.githubusercontent.com/assets/9708050/17094709/9ae789c6-5216-11e6-9372-e9dc9f934c97.png)

That is the picture of our Whirled instance. The loading is on a constant 80%, so my team was just wondering if there was a way to resolve this? We've tested the "./bin/msoyclient" command and we received this error:

```
user@user-VirtualBox:~/Desktop/msoy$ ./bin/msoyclient
----> Preloader DID work.
Error #2046: The loaded file did not have a valid signature.
Failed to load RSL http://[We Are Trying To Make The Link Private]/clients/framework_3.3.0.4852.swz
Failing over to RSL http://[We Are Trying To Make The Link Private]/clients/framework_3.3.0.4852.swf
Flex Error #1001: Digest mismatch with RSL http://[We Are Trying To Make The Link Private]clients/framework_3.3.0.4852.swf. Redeploy the matching RSL or relink your application with the matching library.
```

**Comment by TWSICommunity** [comment]
Shadowsych it's world-client.swf not world-server.swf. XD

**Comment by Shadowsych** [comment]
We got it working by clearing our cookies and history.

**Comment by Shadowsych** [comment]
We do not know how to properly fix this issue; we've attempted to clear cookies and history but that didn't work.

**Comment by TWSICommunity** [comment]
What we tried is creating a new msoy folder, then building it which successfully worked. Then we ran the server but it was stuck at 80% loading in our new whirled instance. We need to know how to fix this properly so that when we make another instance we know how to do it. We need your help samskivert if your not busy and all.
