### ISSUE TITLE
Whirled Code Licensing Questions 

### ISSUE THREAD

**Issue by VoxRatio** [greyhavens/msoy#3]
Hey Michael,

Sorry if my questions are getting annoying. I was wondering what license the Whirled source code is under and any conditions for using it. Are we allowed to sell bars to pay hosting fees, etc.?

**Comment by samskivert** [comment]
No problem. I had neglected to put the LICENSE files in there, so this is a good reminder.

Whirled and all related code is licensed under the BSD license, which means you're allowed to do whatever you want with it, and even charge money for the resulting software or service, but you just have to have a place in the client for your service (like an about dialog or something) that says something like:

```
Foozle Bazzle is adapted from the Whirled project: https://github.com/greyhavens/msoy/

See the license for the Whirled project for disclaimers of liability with regard to this code.
```
