### ISSUE TITLE
Hi mikeness.

### ISSUE THREAD

**Issue by TWSICommunity** [greyhavens/msoy#34]
Hi mikeness, how are you today.

I have a picture to show you that may occur to you but do you realize that shadowsych https://github.com/Shadowsych is selling your files to people over $20 even though this is open source. If you want to know more just email me at gamewolf10@gmail.com. This is a serious note you need to see because your project is being sold without permission. And if you do not own this anymore could you direct me to the new owner. My www.syncedonline.com wasn't shut down but more like moved to a different spot. Thank you for your time and I hope to see your response.

**Comment by Shadowsych** [comment]
I think you're mistaken. I'm not selling the most code. I'm selling a Google document that contains detailed instructions to make a msoy server. Also, the BSD license allows me to make profit from the msoy project, so I'm allowed to sell this Google document.

**Comment by TWSICommunity** [comment]
Oh if you were just selling the document then there's no problem I guess. Sorry for the misunderstanding then if that's what you were doing shadowsych. Nvm then I was mistaken...
