### ISSUE TITLE
Whirled uses all IP Addresses to start up.

### ISSUE THREAD

**Issue by IceTheCoyote** [greyhavens/msoy#37]
Is there a way you can bind just one IP Address instead of it just grabbing all of your IP Addresses at once? The IP I want it to be binded in is 10.244.47.86 but Whirled wants 0.0.0.0 but that's not what I want it to be binded in. Do I need to setup some sort of setting for jetty which is what Whirled uses?

**Comment by IceTheCoyote** [comment]
To add into my reply i'm trying to run my Apache server and Whirled on the same machine with both ports since I have separate IP Addresses to make it work.

**Comment by samskivert** [comment]
Unfortunately it's not easy to tell the MSOY server to bind to a particular address. It requires modifying the code. You'll have to modify MsoyServer.java and add a method that overrides a method from PresentsServer:

```java
    protected String getBindHostname () {
        return "10.244.47.86";
    }
```

I'm also not 100% sure that it will work if you provide an IP address rendered as a string from that method. You may have to create an entry in `/etc/hosts` on the server machine that maps to the desired IP address and then return the name of that host entry from `getBindHostname`. So if the direct IP address does not work, try that.
