### ISSUE TITLE
Unable to resolve 6 Three Rings artifacts

### ISSUE THREAD

**Issue by FlowShift** [greyhavens/msoy#7]
Hi,

The following artifacts are missing:

com.threerings:orth:jar:0.9
com.threerings:whirled-code:jar:1.1-SNAPSHOT
com.threerings:threerings:jar:1.1
com.threerings:database-utils:jar:1.0
com.threerings:toybox:jar:1.0
com.threerings:underwire:jar:1.0

for artifact:

com.threerings.msoy:msoy:jar:1.0-SNAPSHOT

Could you please point me in the direction of these jars?
Thanks.

**Comment by TWSICommunity** [comment]
I had the same problem with that too... Can't get 7 artifacts from building it (without the errors but just those 7 artifacts missing....)

**Comment by MushroomCassette** [comment]
I understand that you're extremely busy Michael, but we would truly appreciate your help with these dependancies. It seems that they've been removed from the maven repo.

**Comment by samskivert** [comment]
Unfortunately public releases were not made for some specific versions of artifacts, and not at all for some projects. The five versioned releases you need are in this jar file:

https://www.dropbox.com/s/efhxy89g4wba1dt/msoy-artifacts.jar?dl=0

You'll need to unpack them wherever your Maven repository is (probably your home directory) and it will put the right files into the right place in your Maven repository such that the build will work. The whirled-code jar you can install yourself by cloning this Github repo:

https://github.com/greyhavens/whirled-api

and running `mvn install` at the top level of that project.
