### ISSUE TITLE
thane folder doesn't exist in the project folder?

### ISSUE THREAD

**Issue by TWSICommunity** [greyhavens/msoy#9]
thane folder does not exist somehow in the project? Does it have to do with the entire thing of building whirled? It's just a question that I want answered that's all. I am not posting compile errors because I don't have the "egrep" error (Using Ubuntu which seems to work wonderfully when building whirled.) It's ok I just wanted to know what the thane folder in the project was for.

**Comment by TWSICommunity** [comment]
You can always close this if this issue has nothing to do with it.

**Comment by samskivert** [comment]
Thane is a separate project that you have to check out into the appropriate place in the msoy directory.

https://github.com/greyhavens/thane

**Comment by TWSICommunity** [comment]
Alright I will look into that because I seemed interested in this whirled source code, thanks for the reply though. +1
